version: '3'

services:
  db:
    image: alpine:3.21
    container_name: pawly_db
    volumes:
      - bd_data:/data
    command: sh -c "mkdir -p /data && chmod 777 /data && echo 'Contenedor de base de datos listo' && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "test", "-d", "/data"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: pawly_web
    ports:
      - "8000:8000"
    volumes:
      - bd_data:/app/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  bd_data:
